services:
  - type: web
    name: crypto-scalper-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
